[general]
runDir = "../scan1_from_metal/b{beta}_U{U}"
codeDir = "/home/hhpstobb/lDGA/codes"
CFLAGS = "-O3 -xHost"
verbose = false
cluster = "berlin"
custom_slurm_lines = ""
custom_init_andpar_file = "../scan1_from_metal/hubb.andpar"
custom_init_andpar_vals_only = true
custom_module_load = "module restore ed_dmft"
custom_conda_env = "p3"
auto_continue = true

[parameters]
beta = 15.0
U = 3.2
t = 0.2
mu = "HF"
ns = 5

[ED]
skip = false
w_min = -12.0
w_max = 12.0
deltino = 0.01
imaxmu = 0
deltamu = 0.0
iterations = 250
conv_param = 0.007
nprocs = 100

[Vertex]
skip = false
nmpara = 30
nFermiFreq = 145
nBoseFreq = 144

[Susc]
skip = false
nBoseFreq = 10000

[Trilex]
skip = false
nmpara = 30
nFermiFreq = 145
nBoseFreq = 144

[Postprocess]
skip = false
data_bakup = "mv"
output_format = "tar,parquet"
