[general]
runDir = "../tests/test_02"
codeDir = "/home/hhpstobb/lDGA/codes"
CFLAGS = "-O3 -xHost"
verbose = false
cluster = "berlin"
custom_slurm_lines = "-A hhp00048"
custom_init_andpar_file = "../tests/hubb.andpar"
custom_init_andpar_vals_only = true
custom_module_load = "module restore ed"
custom_conda_env = "p3"
auto_continue = true

[parameters]
beta = 25.0
U = 2.0
t = 0.2
mu = "HF"
ns = 5

[ED]
skip = false
w_min = -12.0
w_max = 12.0
deltino = 0.01
imaxmu = 0
deltamu = 0.0
iterations = 50
conv_param = "1.d-13"
nprocs = 60

[Vertex]
skip = false
nmpara = 30
nFermiFreq = 3
nBoseFreq = 2

[Susc]
skip = false
nBoseFreq = 10000

[Trilex]
skip = false
nmpara = 30
nFermiFreq = 3
nBoseFreq = 2

[Postprocess]
skip = false
keep_only_data = false
data_bakup = "mv"
output_format = "tar,text"
split = true

[lDGAFortran]
skip = false
LQ = 20
Nint = 20
k_range = 10
only_chisp_ch = false
only_lambda_sp = true
only_positive_ch = true
only_positive_sp = true
