[general]

runDir = "../full_calc_test_automated_1"
codeDir = "../codes"
CFLAGS = "-O3 -xHost"
verbose = false
cluster = "berlin"          # local|berlin|goettingen|physnet| TODO: this is very hacky right now
custom_slurm_lines = ""     # example: "#SBATCH -A hhp00048\n"
custom_andpar_file = ""     # example: "../old1/hubb.andpar"


[parameters]
beta    = 15.0     # inverse temperature
U       = 2.0      # Hubbard U
t       = 0.20     # hopping
mu      = 1.0      # chemical potential
ns      = 5        # Number of sites including imurity

[ED]
skip        = false
w_min       = -12.0
w_max       = 12.0
deltino     = 0.01
imaxmu      = 0
deltamu     = 0.0
iterations  = 250
conv_param  = 0.007
nprocs      = 100

#ifix(0,1), <n>,   inew, iauto 
#th0 , iexp (insignificant)
#nmin, nmax
#lambda, w0, nph

#initial anderson parameters here?

[Vertex]
skip        = false
nmpara      = 30
nFermiFreq  = 80   # number of positive fermionic matsubara Frequencies, nBose will be nFermi-1
nBoseFreq   = 79

[Susc]
skip        = false
nBoseFreq   = 10000

[Trilex]
skip        = false
nmpara      = 30
nFermiFreq  = 80   # number of positive fermionic matsubara Frequencies, nBose will be nFermi-1
nBoseFreq   = 79
