[general]
runDir = "../tests/cut_medium_beta{beta}_U{U}"
codeDir = "/home/hhpstobb/lDGA/codes"
CFLAGS = "-O3 -xHost"
verbose = false
cluster = "berlin"
custom_slurm_lines = "-A hhp00048"
custom_init_andpar_file = "../hubb.andpar"
custom_init_andpar_vals_only = true
custom_module_load = "module restore ed"
custom_conda_env = "p3"
auto_continue = true
restart_after_success = true   # do not attempt to restart already completed jobs

[parameters]
beta = 25
U = 1.0
mu = "HF"
ns = 5
bethe = false
Dimensions = 3
symm = true

[ED]
skip = false
w_min = -12.0       # unwichtig
w_max = 12.0        # unwichtig
deltino = 0.01      # unwichtig
imaxmu = 0          # unwichtig        
deltamu = 0.0       # unwichtig
iterations = 80
conv_param = "1.d-13"

[Vertex]
skip = false
# freqList can be either a path to a frequency list or
# "F1:F2,B1:B2" for N1 to N2 (integer) fermionic and B1 to B2 bosonic.
freqList = "-3:4,-4,4"
nprocs = 192

[Susc]
skip = false
nmpara = 30
nBoseFreq = 10000

[Trilex]
skip = false
nmpara = 30
nFermiFreq = 41
nBoseFreq = 40

[Postprocess]
skip = false
keep_only_data = false
data_bakup = "cp"
output_format = "tar,text"
split = true

[lDGA]
LQ = 4          # FFT requires: 2 * LQ - 2 == Nint
Nint = 4        # 
k_range = 4     # Sigma FFT requires: k_range = LQ - 1
only_chisp_ch = false
only_lambda_sp = true
only_positive_ch = true
only_positive_sp = true
kInt = "FFT" # possible values are naive, gl-n (n being the order of the Gauss Legendre integration) or FFT

[lDGAFortran]
skip = true

[lDGAJulia]
skip = true
tail_corrected = "both" # possible values are "yes/no/both"

[lDGAPost]
delete_calc = false # WARNING: this will delete all logfiles and intermediate results such as F and chi
result_vars = "chi_q"
