[general]

runDir = "../full_calc_test_b{beta}_U{U}"
codeDir = "../codes"
CFLAGS = "-O3 -xHost"
verbose = false
cluster = "berlin"          # local|berlin|goettingen|physnet| TODO: this is very hacky right now

custom_slurm_lines = ""     # example: "#SBATCH -A hhp00048\n"
custom_init_andpar_file = "../full_calc_test_b15_U5.6/ed_dmft/hubb.andpar"         # example: "../old1/hubb.andpar"
custom_init_andpar_vals_only = true  # if set to false, file is copied. otherwise only start values are used


[parameters]
beta    = 15.0     # inverse temperature
U       = 22.2     # Hubbard U
t       = 0.20     # hopping
mu      = "HF"     # chemical potential as float or "HF" for half filling
ns      = 5        # Number of sites including imurity

[ED]
skip        = false
w_min       = -12.0
w_max       = 12.0
deltino     = 0.01
imaxmu      = 0
deltamu     = 0.0
iterations  = 250
conv_param  = 0.007
nprocs      = 100

#ifix(0,1), <n>,   inew, iauto 
#th0 , iexp (insignificant)
#nmin, nmax
#lambda, w0, nph

#initial anderson parameters here?

[Vertex]
skip        = true
nmpara      = 30
nFermiFreq  = 80   # number of positive fermionic matsubara Frequencies, nBose will be nFermi-1
nBoseFreq   = 79   # TODO: this should be fixed at nfermi - 1       

[Susc]
skip        = true
nBoseFreq   = 10000

[Trilex]
skip        = true
nmpara      = 30
nFermiFreq  = 80   # number of positive fermionic matsubara Frequencies, nBose will be nFermi-1
nBoseFreq   = 79


[Postprocess]
skip        = true
