[general]

runDir = "../full_calc_test_automated"
codeDir = "../codes"
CFLAGS = "-O3"
verbose = false
clusterType = "berlin" # local|berlin|goettingen|physnet| TODO: this is very hacky right now


[parameters]
beta    = 15.0     # inverse temperature
U       = 5.0      # Hubbard U
t       = 0.204    # hopping
mu      = 1.0      # chemical potential
ns      = 5        # Number of sites including imurity

[ED]
nFermiFreq  = 80   # number of positive fermionic matsubara Frequencies, nBose will be nFermi-1
nBoseFreq   = 79
w_min       = -12.0
w_max       = 12.0
deltino     = 0.01
imaxmu      = 0
deltamu     = 0.0
iterations  = 250
conv_param  = 0.007

#ifix(0,1), <n>,   inew, iauto 
#th0 , iexp (insignificant)
#nmin, nmax
#lambda, w0, nph

#initial anderson parameters here?

[Vertex]

[Susc]

[Trilex]
