[general]

runDir = "../full_calc_test_automated_2"
codeDir = "../codes"
CFLAGS = "-O3 -xHost"
verbose = false
cluster = "berlin" # local|berlin|goettingen|physnet| TODO: this is very hacky right now


[parameters]
beta    = 25.0     # inverse temperature
U       = 12.0      # Hubbard U
t       = 0.20     # hopping
mu      = 6.0      # chemical potential
ns      = 7        # Number of sites including imurity

[ED]
skip        = false
w_min       = -12.0
w_max       = 12.0
deltino     = 0.01
imaxmu      = 0
deltamu     = 0.0
iterations  = 250
conv_param  = 0.007
nprocs      = 100

#ifix(0,1), <n>,   inew, iauto 
#th0 , iexp (insignificant)
#nmin, nmax
#lambda, w0, nph

#initial anderson parameters here?

[Vertex]
skip        = false
nmpara      = 30
nFermiFreq  = 80   # number of positive fermionic matsubara Frequencies, nBose will be nFermi-1
nBoseFreq   = 79

[Susc]
skip        = false
nBoseFreq   = 10000

[Trilex]
skip        = false
