[general]
runDir = "../tests/tt1"
codeDir = "/home/hhpstobb/lDGA/codes"
CFLAGS = "-O3 -xHost"
verbose = false
cluster = "berlin"
custom_slurm_lines = "-A hhp00048"
custom_init_andpar_file = "../tests/hubb.andpar"
custom_init_andpar_vals_only = true
custom_module_load = "module restore ed"
custom_conda_env = "p3"
auto_continue = true
restart_after_success = false   # do not attempt to restart already completed jobs

[parameters]
beta = 15.0
U = 0.5
mu = "HF"
ns = 5
Dimensions = 3

[ED]
skip = false
w_min = -12.0       # unwichtig
w_max = 12.0        # unwichtig
deltino = 0.01      # unwichtig
imaxmu = 0          # unwichtig        
deltamu = 0.0       # unwichtig
iterations = 80
conv_param = "1.d-13"
nprocs = 60

[Vertex]
skip = true
nmpara = 30
nFermiFreq = 61
nBoseFreq = 60

[Susc]
skip = true
nBoseFreq = 10000

[Trilex]
skip = true
nmpara = 30
nFermiFreq = 11
nBoseFreq = 10

[Postprocess]
skip = true
keep_only_data = false
data_bakup = "mv"
output_format = "tar,text"
split = true

[lDGA]
LQ = 4
Nint = 4
k_range = 4
only_chisp_ch = false
only_lambda_sp = true
only_positive_ch = true
only_positive_sp = true
kInt = "FFT" # possible values are naive, gl-n (n being the order of the Gauss Legendre integration) or FFT

[lDGAFortran]
skip = true

[lDGAJulia]
skip = true
tail_corrected = "both" # possible values are "yes/no/both"

[lDGAPost]
delete_calc = false # WARNING: this will delete all logfiles and intermediate results such as F and chi
result_vars = "chi_q"
