[general]
runDir = "/home/hhpstobb/lDGA/data/test_b{beta}_U{U}"
codeDir = "/home/hhpstobb/lDGA/codes"
CFLAGS = "-W -Wsurprising -Wall -pedantic"#"-O3 -xHost"
verbose = false
cluster = "berlin"
custom_slurm_lines = "-A hhp00048"
custom_init_andpar_file = "/home/hhpstobb/lDGA/data/test_reference_b25.0_U1.0/data/hubb.andpar"
custom_init_andpar_vals_only = true
custom_module_load = "module restore ed"
custom_conda_env = "p3"
auto_continue = true
restart_after_success = false   # do not attempt to restart already completed jobs

[parameters]
beta = 25.0
U = 1.0
mu = "HF"
ns = 5
bethe = false
Dimensions = 3
symm = true

[ED]
skip = true
w_min = -12.0       # unwichtig
w_max = 12.0        # unwichtig
deltino = 0.01      # unwichtig
imaxmu = 0          # unwichtig        
deltamu = 0.0       # unwichtig
iterations = 800
conv_param = "1.d-13"

[Vertex]
skip = false
nmpara = 30
freqList_fermi = 5      # either "start:stop" or "filename"
freqList_bose =         # either "start:stop" or "filename"

[Susc]
skip = true
nBoseFreq = 10000

[Trilex]
skip = true
nmpara = 30
nFermiFreq = 81
nBoseFreq = 80

[Postprocess]
skip = true
keep_only_data = false
data_bakup = "cp"
output_format = "tar,text"
split = true

[lDGA]
LQ = 16
Nint = 30
k_range = 15
only_chisp_ch = false
only_lambda_sp = true
only_positive_ch = true
only_positive_sp = true
kInt = "FFT" # possible values are naive, gl-n (n being the order of the Gauss Legendre integration) or FFT

[lDGAFortran]
skip = true

[lDGAJulia]
skip = true
tail_corrected = "both" # possible values are "yes/no/both"

[lDGAPost]
delete_calc = false # WARNING: this will delete all logfiles and intermediate results such as F and chi
result_vars = "chi_q"
